---
title: "Theory of mind"
author: "Likan Zhan"
date: '2018-06-06'
lastmod: "`r Sys.Date()`"
bibliography: [../bibliography/paradigm.bib]
link-citations: yes
csl: [../bibliography/apa-old-doi-prefix.csl]
output:
  blogdown::html_page:
    toc: true
slug: []
tags: []
categories: []
---

# 1. Theory of Mind (TOM)

Theory of Mind is the human capacity to comprehend that other people hold beliefs and desires and that these may differ from one's own beliefs and desires. Understanding others’ mental states is a crucial skill that enables the complex social relationships that characterize human societies.

# 2. False belief task

## 2.1 Change-of-location false belief task

In a typical change-of-location false belief task, participants see short videos in which a target object of some relevance to a protagonist changes location. This change of location is either witnessed or unwitnessed by the protagonist. If the the change of location is witnessed by the protagonist and the participants, they will have the same mental state that the object is in the new location. If the change of the location is witnessed by the participants but not by the protagonist, then the participants and the protagonist have different mental states: the participant know that the object is in the new locaton, while the protagonist falsely believes that the object is still in the original location.

When particiapnts are asked to answer the question, `where do you think the protagonist will search for the object?`, if they understand that their own mental state is different from the protagonist's, and understand that the protagonist' behavior should be consistent to his/her onw mental state, then the participants should chosse the original location.

The response variable is either the overt behavioal resposnes (explicit theory of mind), or the covert eye-movements (implicit theory of mind).

## 2.2 Recent Applications

- 01. @PNAS1803505115

Eighteen- and 36-month-old children observed a displacement event, which was witnessed by a person wearing sunglasses (Experiment 1). Having later discovered that the sunglasses were opaque, 36-month-olds correctly inferred that the person must have formed a false belief about the location of the objects and used this inference in resolving her referential expressions. They successfully performed retrospective revision in the opposite direction as well, correcting a mistakenly attributed false belief when this was necessary (Experiment 3). Thus, children can compute beliefs retrospectively, based on episodic memories, well before they pass explicit false-belief tasks. Eighteen-month-olds failed in such a task, suggesting that they cannot retrospectively attribute beliefs or revise their initial belief attributions. However, an additional experiment provided evidence for prospective track- ing of false beliefs in 18-month-olds (Experiment 2). Beyond identifying two different modes for tracking and updating others' mental states early in development, these results also provide clear evidence of episodic memory retrieval in young children.


# 3. References
