---
title: "R-网页爬虫：分析HTML代码"
author: "王诗翔"
date: "2018-09-17"
lastmod: "`r Sys.Date()`"
slug: ""
categories: [r]
tags: ["r", "爬虫"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, dev = "png", comment = "#>")
#Sys.setenv("LANGUAGE"="EN") # Embed this for outputing English message
#Sys.setlocale('LC_ALL','C') # Embed this directly in the Rmarkdown script that contains the Chinese character comment
options(digits=3)
options(max.print=200)
```

前一篇文章我们学习了选择器（CSS和XPath）。

我们可以从<https://cran.rstudio.com/web/packages/available_packages_by_name.html>这个网页上获取所有可用的R扩展包。网页看起来简单，想知道选择器的表达式，在页面右击，选择菜单中的审查元素选项（大部分浏览器都有），然后就会出现检查面板。我们可以看到网页底层的HTML代码。

HTML包含唯一的`<table>`，因此可以直接将CSS选择器设为`table`，再用`html_table()`提取表格并返回一个数据框：

```{r}
library(rvest)
page = read_html("https://cran.rstudio.com/web/packages/available_packages_by_name.html")
pkg_table = page %>% 
    html_node("table") %>% 
    html_table(fill = TRUE)
head(pkg_table, 5)
```

这里原始表没有表头。结果数据框使用了默认表头，并且第一行是空的，下面代码解决这个问题：

```{r}
pkg_table = pkg_table[complete.cases(pkg_table), ]
colnames(pkg_table) = c("name", "title")
head(pkg_table, 3)
```

我开发的包在里面吗？随便看几个

```{r}
pkg_table[pkg_table$name %in% c("UCSCXenaTools", "UCSCXenaShiny", "ezcox", "metawho"),]
```

