---
title: "字符串操作"
author: "王诗翔"
date: "2018-08-15"
lastmod: "`r Sys.Date()`"
slug: ""
categories: [r]
tags: [r, stringr]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, dev = "png", comment = "#>")
#Sys.setenv("LANGUAGE"="EN") # Embed this for outputing English message
#Sys.setlocale('LC_ALL','C') # Embed this directly in the Rmarkdown script that contains the Chinese character comment
options(digits=3)
options(max.print=200)
```

## 打印

```{r}
"Hello world!"
```

```{r}
print("Hello world!")
```


不带索引

```{r}
cat("Hello world!")
```

```{r}
message("Hello world!")
```

## 连接

```{r}
paste("Hello", "world!")
paste("Hello", "world", sep = "-")
```

```{r}
paste0("Hello", "World")
```

```{r}
paste(c("A", "B"), c(1,2))
```

```{r}
paste(c("A", "B"), c(1,2), collapse = ",", sep = "")
```

## 转换

### 转换大小写

```{r}
toupper("Hello")
```

```{r}
tolower("HeLLo")
```

### 字符计数

```{r}
nchar("Hello!")
```


### 清除首末空白

```{r}
trimws(c(" P ", " S", "P "))
```

### 取子串

```{r}
dates = c("Jan 3", "Feb 10", "Nov 15")
substr(dates, 1, 3)
substr(dates, 5, nchar(dates))
```

```{r}
substring(dates, 5)
```

### 切分

```{r}
strsplit("a,bb,ccc", split=",")
```

```{r}
students = strsplit(c("Tony, 26, Physics", "James, 25, Economics"), split = ",")
students
```

```{r}
students_matrix = do.call(rbind, students)
students_matrix
```


切空字符

```{r}
strsplit(c("hello", "world"), split = "")
```

## 格式化日期/时间

返回当前日期和时间：

```{r}
Sys.Date()
Sys.time()
```

### 解析为日期与时间

```{r}
as.Date(1000, "1970-01-01")
```

```{r}
my_date = as.Date("2018-08-15")
my_date
```

```{r}
my_date + 3
my_date - 2
```

```{r}
my_date - as.Date("2015-12-20")
```

```{r}
my_time = as.POSIXct("2018-08-15 22:11:20")
my_time
```

```{r}
# 改变的是秒
my_time + 10
```

```{r}
as.Date("2015.04.02", format = "%Y.%m.%d")
```

```{r}
strptime("7/25/2018 08:04:23", "%m/%d/%Y %H:%M:%S")
```

日期到字符串

```{r}
my_date
as.character(my_date, format = "%Y.%m.%d")
```

其实调用`format()`本身就可以做到

```{r}
format(my_date, format = "%Y.%m.%d")
```

## 字符串匹配

```{r}
library(stringr)
strings <- c(" 219 733 8965", "329-293-8753 ", "banana", "595 794 7569",
  "387 287 6718", "apple", "233.398.9187  ", "482 952 3315",
  "239 923 8115 and 842 566 4692", "Work: 579-499-7527", "$1000",
  "Home: 543.355.3679")
phone <- "([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})"
str_extract(strings, phone)
```

`()`用于对数据进行标记。

```{r}
str_match(strings, phone)
```

```{r}
# Extract/match all
str_extract_all(strings, phone)
```

```{r}
str_match_all(strings, phone)
```
