---
title: "2019 年度总结"
author: "王诗翔"
date: "2020-01-01"
lastmod: "`r Sys.Date()`"
slug: ""
categories: [thinking]
tags: [r, python, life, summary]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, dev = "png", comment = "#>")
#Sys.setenv("LANGUAGE"="EN") # Embed this for outputing English message
#Sys.setlocale('LC_ALL','C') # Embed this directly in the Rmarkdown script that contains the Chinese character comment
options(digits=3)
options(max.print=200)
```

2019 年过去了，我把自己的 GitHub 仓库清理了一遍，总结过去一年自己的收获和思考。

## 参与发表的文献

2019 年我参与发表了 5 篇科学文献，其中 4 篇 SCI，另 1 篇是我将去年开发的 UCSCXenaTools 投到了 JOSS。
我心里最满意的是 UCSCXenaTools 经过 rOpenSci 的代码审查后快速被 JOSS 收录并发表，这一年我一直保证良好的维护状态，目前有上万次的下载安装，希望未来能够帮助更多的癌症研究人员。

其他 4 篇有 3 篇是研究型文章，我通过它们成长了很多，包括课题的分析思路、代码的实现等。但个人仍感觉不够深入和
细致，自己对于研究背景知识的理解还大有欠缺，希望新的一年有更多的成长。

- [The predictive power of tumor mutational burden in lung cancer immunotherapy response is influenced by patients’ sex, *IJC*](https://www.ncbi.nlm.nih.gov/pubmed/30972745)
- [The UCSCXenaTools R package: a toolkit for accessing genomics data from UCSC Xena platform, from cancer multi-omics to single-cell RNA-seq, *JOSS*](https://www.theoj.org/joss-papers/joss.01627/10.21105.joss.01627.pdf)
- [Sex Differences in Cancer Immunotherapy Efficacy, Biomarkers, and Therapeutic Strategy, *Molecules*](https://www.mdpi.com/1420-3049/24/18/3214)
- [Ras Downstream Effector GGCT Alleviates Oncogenic Stress, *iScience*](https://www.sciencedirect.com/science/article/pii/S2589004219302639)
- [Antigen presentation and tumor immunogenicity in cancer immunotherapy response prediction, *eLife*](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6879305/)

遗憾的是凭借前 4 篇文章和去年发表的一篇 Oncogene，我仍然未能入选 2019 年的国家奖学金的评选，
可能以后再也不会像去年那样有心去争取了。

## 开发和维护的工具包或脚本

2019 年我开发和维护了一系列的工具或脚本，既是为了帮助自己，也希望能够帮助他人。

- [ezcox](https://github.com/ShixiangWang/ezcox) - 批量实现 Cox 分析
- [metawho](https://github.com/ShixiangWang/metawho) - 实现亚组元分析
- [UCSCXenaTools](https://github.com/ropensci/UCSCXenaTools) - 获取 UCSC Xena 数据库数据集
- [UCSCXenaShiny](https://github.com/openbiox/XenaShiny) - 以 Shiny 应用的方式查看和下载 UCSC Xena 数据库数据集
- [contribution](https://github.com/openbiox/contribution) - 贡献表格的 ggplot2 实现（兴趣所致）
- [DoAbsolute](https://github.com/ShixiangWang/DoAbsolute) - 并行调用 ABSOLUTE 实现拷贝数分析
- [sigminer](https://github.com/ShixiangWang/sigminer) - 基因组变异 Signature 分析（已开发一年，希望新的一年发表）
- [loon](https://github.com/ShixiangWang/loon) - 懒人工具箱，用于本地操作远程主机实现一些通用任务、PBS 计算和批处理等（目前接近 18K 下载安装）
- [yq](https://github.com/openbiox/yq) - 语雀的 R API，兴趣所致，实现了简单的一些功能，目前没有继续整了
- [flymaps](https://github.com/ShixiangWang/flymaps) - VSCode 快捷键插件，用于数据分析（现在还非常简单）
- [install_GISTIC](https://github.com/ShixiangWang/install_GISTIC) - 一键安装 GISTIC2.0 用于拷贝数分析

## 贡献的工具

我还贡献了一些已有的项目，包括增加特性、修复 bug、回答问题等等。

- [copynumber](https://github.com/ShixiangWang/copynumber) - 支持 hg38
- [maftools](https://github.com/PoisonAlien/maftools) - 修了一些 bug 和新增了一些特性
- [forestmodel](https://github.com/NikNakk/forestmodel/) - 修了一些 bug 和新增了一些特性

## 翻译

2019 年我做了一些翻译工作，包括 R 和 Python。

- [Cookbook for R 中文版](https://github.com/openbiox/Cookbook-for-R-Chinese) - 一本很不错的 R 语言学习和参考手册
- [使用Bioconda辅助生物信息学软件安装：一个简短的教程](https://github.com/XSLiuLab/bioconda-tutorial)
- [利用Python进行数据分析（第二版）](https://github.com/openbiox/py4ds-CN) - 这个我是搬运工，后续需要进一步修改

## 展望与计划

过去一年安然度过，累也充实。新的一年，我希望能够尝试更多可能。

### 课题和研究内容

- [neopeptides](https://github.com/ShixiangWang/neopeptides) - 尝试开发工具用于肿瘤新抗原一些属性的解读
- [sigminer](https://github.com/ShixiangWang/sigminer) - 这个工具在今年能够顺利发表并成为领域的标准工具之一吗？
- [ImmuneDR](https://github.com/ShixiangWang/ImmuneDR) - 免疫组学分析常用数据集的收集和整理，希望有更多相关人员参与

### 兴趣

- [UCSCXenaShiny](https://github.com/openbiox/XenaShiny) - 很久之前就有重构的打算，一些设计也已经经过讨论。接下来会花更多的时间带领 XenaShiny 小队完成目标。 
- [pyshields](https://github.com/ShixiangWang/pyshields) - Python README 能否肆意添加和转换 badge 呢？
- [flymaps](https://github.com/ShixiangWang/flymaps) - 维护和拓展相关的快捷键
- [GoArduino](https://github.com/ShixiangWang/GoArduino) - 尝试学习下硬件相关编程和设计

### 学习

- [shinyshining](https://github.com/ShixiangWang/shinyshining) - 学习 Shiny，并将它应用于 UCSCXenaShiny 的开发
- [Pythonshining](https://github.com/ShixiangWang/Pythonshining) - 学习 Python 和项目开发
- [SnakeFlow](https://github.com/ShixiangWang/SnakeFlow) - 学习 Snakemake，收集整理目前已有的流程，编写一些有用的
分析流程

### 翻译

- [shiny-book](https://github.com/ShixiangWang/shiny-book) - 尝试翻译 Shiny 官方书籍
- [gentle-ggplot2](https://github.com/ShixiangWang/gentle-ggplot2) - 向大家系统的介绍 ggplot2 
- [mlr3-book](https://github.com/ShixiangWang/mlr3book) - 学习使用 R 进行机器学习并尝试翻译
- [tidy-eval](https://github.com/ShixiangWang/tidyeval-chinese) - 向大家系统介绍非标准计算

最后希望新的一年自己和家人身体健康，爱情美满。
