---
title: "Linear model and t test"
# subtitle: "A Programming Language"
author: "Likan Zhan"
date: '2018-10-12'
lastmod: "`r Sys.Date()`"
bibliography: [../bibliography/paradigm.bib]
link-citations: yes
csl: [../bibliography/apa-old-doi-prefix.csl]
output:
  blogdown::html_page:
    toc: true
slug: []
tags: []
categories: []
---

# 1. A brief description

   This post will summarize the advancement of using R to analyze data obtained in behavioral and relevant areas.

# 2. Recent Applications

01.

```{r, label = "data-source", echo = FALSE}
set.seed(5)
x  <- rnorm(10)
x1 <- x + rnorm(10)
x2 <- x + 1 + rnorm(10)
myDat <- data.frame(
  Y = c(x1, x2),
  X = c(rep("x1", 10), rep("x2", 10)),
  Subj = rep(paste0("S", seq(1, 10)), 2))
```

```{r, echo = TRUE}
myDat
```

```{r}
t1 <- t.test(Y ~ X, data = myDat, paired = FALSE)
print(t1)
```

```{r}
fm1 <- lm(Y ~ X, data = myDat)
summary(fm1)
```

```{r}
t2 <- t.test(Y ~ X, data = myDat, paired = TRUE)
print(t2)
```

```{r}
suppressMessages(library(lme4))
fm2 <- lmer(Y ~ X + (1 | Subj), data = myDat)
model.matrix(fm2, "random")
summary(fm2)
fm3 <- lm(Y ~ X + Subj, data = myDat)
summary(fm3)
```

02. To be added


Appendix

```{r, label = "data-source", echo = TRUE}
```

# 3. References
