---
title: "R Used in Literature"
# subtitle: "A Programming Language"
author: "Likan Zhan"
date: '2018-10-12'
lastmod: "`r Sys.Date()`"
bibliography: [../bibliography/paradigm.bib]
link-citations: yes
csl: [../bibliography/apa-old-doi-prefix.csl]
output:
  blogdown::html_page:
    toc: true
slug: []
tags: []
categories: []
---

# 1. A brief description

   This post will summarize the advancement of using R to analyze data obtained in behavioral and relevant areas.

# 2. Recent Applications

01. Use null model to do the statistics [@RN1544]

```{r, label = "data-source", echo = FALSE}
Cnd_Prdct <- structure(list(Prop = c(0.39585635359116, 0.70073664825046,
0.610405156537753, 0.557918968692449, 0.425111812680873, 0.460589318600368,
0.533519553072626, 0.816942909760589, 0.675046040515654, 0.691252302025783,
0.378453038674033, 0.620461720599842, 0.472296764009471, 0.204590897132334,
0.786266771902131, 0.610497237569061, 0.752617732175743, 0.547697974217311,
0.433149171270718, 0.707044198895028, 0.713351749539595, 0.72744014732965,
0.529281767955801, 0.66798210997106, 0.387845303867403, 0.532136279926335,
0.804307116104869, 0.652394106813996, 0.489134438305709, 0.445672191528545
)), row.names = c(4L, 6L, 10L, 12L, 16L, 18L, 20L, 22L, 24L,
26L, 28L, 30L, 34L, 36L, 38L, 40L, 42L, 44L, 46L, 48L, 50L, 52L,
54L, 56L, 58L, 60L, 62L, 66L, 70L, 72L), class = "data.frame")
```

```{r, echo = TRUE}
str(Cnd_Prdct)
```

```{r}
Prop  <- Cnd_Prdct$Prop
ptp <- car::powerTransform(Prop)
summary(ptp)
```

```{r}
Prop  <- Cnd_Prdct$Prop
n     <- length(Prop)
Y_Bar <- 0.5
Y_Hat <- ave(Prop)
SST   <- sum((Prop  - Y_Bar) ^ 2)
SSR   <- sum((Y_Bar - Y_Hat) ^ 2)
SSE   <- sum((Prop  - Y_Hat) ^ 2)
MSR   <- SSR / 1
MSE   <- SSE / (n - 1)
F_val <- MSR / MSE
p_val <- pf(F_val, 1, n - 1, lower.tail = FALSE)
data.frame(
  Soource = c("Regression", "Residual", "Total"),
  Sum_of_Squares = c(SSR, SSE, SST),
  df = c(1, n - 1, n),
  Mean_Square = c(MSR, MSE, NA),
  F_Value = c(F_val, NA, NA),
  p_Value = c(p_val, NA, NA)
)
```

```{r}
Cnd_Prdct $ Prop1  <- Cnd_Prdct $ Prop - 0.5
Cnd_Prdct $ Priori  <- 0.5
```

```{r}
fm1 <- lm(Prop1 ~ 1, data = Cnd_Prdct)
car::Anova(fm1, type = 3)
```

```{r}
fm2 <- lm(Prop - 0.5 ~ 1, data = Cnd_Prdct)
car::Anova(fm2, type = 3)
```

```{r}
fm3 <- lm(Prop ~ 1, offset = Priori, data = Cnd_Prdct)
summary(fm3)
car::Anova(fm3, type = 3)
```

To be added

02. To be added


Appendix

```{r, label = "data-source", echo = TRUE}
```

# 3. References
